version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    ports:
      - "27017:27017"

  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file: .env
